# Generated by Django 2.0.2 on 2018-07-01 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('image', models.ImageField(upload_to='img/', verbose_name='画像')),
                ('is_selected', models.NullBooleanField(verbose_name='当選')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像',
                'db_table': 'images',
            },
        ),
    ]
